services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=$SA_PASS
    volumes:
      - ./mssql_data:/var/opt/mssql
      - ./mssql_backup:/backup
    restart: unless-stopped
    env_file:
      - .env

  mssql-backup:
    image: mcr.microsoft.com/mssql-tools
    profiles:
      - manual
    network_mode: "container:mssql_server"
    environment:
      - SA_PASSWORD=$SA_PASS
    env_file:
      - .env
    volumes:
      - ./mssql_backup:/backup
    restart: "no"

volumes:
  mssql_data:
    driver: local
