
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $ROOT_PASS
      MYSQL_DATABASE: mysql
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    env_file:
      - .env