services:
  app:
    # build: .
    image: GITHUB_IMAGE_NAME
    restart: unless-stopped
    ports:
      - "127.0.0.1:$EXPOSE_PORT:8000"
    env_file:
      - .env
    volumes:
      - ./dpkeys:/root/.aspnet/DataProtection-Keys
      - ./sitemaps:/app/wwwroot/sitemaps
      - ./appsettings.json:/app/appsettings.json